version: '3.1'
services:
  wordpress:
    container_name: wordpress
    image: wordpress
    ports:
      - 80:80      
    restart: always
    environment:
      WORDPRESS_DB_HOST: 172.31.91.22
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - /mnt/nfs_client/:/var/www/html
volumes:
  wordpress:
